spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}


spring.cloud.gateway.server.webmvc.routes[0].id=route-ms-empleado
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/empleados/**

spring.cloud.gateway.server.webmvc.routes[1].id=route-ms-categoria
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/categorias/**

spring.cloud.gateway.server.webmvc.routes[2].id=route-ms-producto-categoria
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/producto-categoria/**

spring.cloud.gateway.server.webmvc.routes[3].id=route-ms-producto
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.server.webmvc.routes[4].id=route-ms-venta
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/ventas/**

spring.cloud.gateway.server.webmvc.routes[5].id=route-ms-detalle-venta
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/detalle-ventas/**

spring.cloud.gateway.server.webmvc.routes[6].id=route-ms-reportes
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/reportes/**
